### ISSUE TITLE
Can't request a deployment when description contains a single quote

### ISSUE THREAD

**Issue by llaske** [NikhilM98/sugarizer-school-portal-server#11]
When a deployment is requested and the description field of the form contains a single-quote, there is an error message "Deployment description is invalid". Removing the single quote fix the issue.

![Peek 26-10-2020 17-15](https://user-images.githubusercontent.com/981841/97198894-a6cb7780-17af-11eb-9e03-b07457bf01a4.gif)

**Comment by NikhilM98** [comment]
It was excluded from the regex as a security measure to prevent XSS attacks on the website.

Here: https://github.com/NikhilM98/sugarizer-school-portal-server/blob/d54a6556f9833e442b72d28923ceb240cc978b08/helper/regexValidate.js#L21-L22

We can implement Sanitization to the description input using HTML sanitization libraries like [DOMPurify](https://github.com/cure53/DOMPurify). Using which, we can replace the special characters with character encodings for those characters.
