### ISSUE TITLE
Selection of a suggested localization doesn't work

### ISSUE THREAD

**Issue by llaske** [NikhilM98/sugarizer-school-portal-server#13]
The localization field is supposed to be an help to type the address but when the user click on a suggested address there is an error message telling that the address is invalid.

![Peek 13-11-2020 22-56](https://user-images.githubusercontent.com/981841/99125044-9e729980-2603-11eb-8a6e-11341b59bcf7.gif)

**Comment by llaske** [comment]
In the example, the problem comes from the single quote character.

**Comment by NikhilM98** [comment]
Fixed in #19
